#!/usr/bin/env python3
"""Generate PNG plots from NMT monitor CSV output."""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Sequence

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


@dataclass
class Sample:
    timestamp: datetime
    total_committed_mb: float
    rss_mb: float
    non_nmt_estimated_mb: float
    jni_likely_estimated_mb: float
    java_heap_committed_mb: float
    thread_committed_mb: float
    code_committed_mb: float
    gc_committed_mb: float
    internal_committed_mb: float
    other_committed_mb: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate PNG chart from NMT monitor CSV")
    parser.add_argument("csv_path", type=Path, help="Path to CSV generated by secp256k1 monitor scripts")
    parser.add_argument("--out", type=Path, default=Path("nmt_plot.png"), help="Output PNG path")
    parser.add_argument("--last", type=int, default=0, help="Plot only the last N samples (0 = all)")
    parser.add_argument("--smooth-window", type=int, default=1, help="Moving-average window (1 = disabled)")
    parser.add_argument("--title", default="NMT vs non-NMT memory", help="Chart title")
    return parser.parse_args()


def _to_float(value: str, default: float = 0.0) -> float:
    if value is None or value == "":
        return default
    return float(value)


def load_samples(csv_path: Path) -> List[Sample]:
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    with csv_path.open("r", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        raise ValueError(f"CSV has no rows: {csv_path}")

    samples: List[Sample] = []
    skipped_rows = 0
    for row in rows:
        epoch_value = row.get("epoch")
        if not epoch_value:
            skipped_rows += 1
            continue

        try:
            epoch = int(epoch_value)
        except ValueError:
            skipped_rows += 1
            continue

        committed = _to_float(row.get("total_committed_mb"))
        rss = _to_float(row.get("rss_mb"))
        non_nmt = _to_float(row.get("non_nmt_estimated_mb"), max(rss - committed, 0.0))
        unknown = _to_float(row.get("unknown_committed_mb"))
        arena_chunk = _to_float(row.get("arena_chunk_committed_mb"))
        jni_likely = _to_float(
            row.get("jni_likely_estimated_mb"),
            _to_float(row.get("internal_committed_mb"))
            + _to_float(row.get("other_committed_mb"))
            + unknown
            + arena_chunk,
        )

        samples.append(
            Sample(
                timestamp=datetime.fromtimestamp(epoch),
                total_committed_mb=committed,
                rss_mb=rss,
                non_nmt_estimated_mb=non_nmt,
                jni_likely_estimated_mb=jni_likely,
                java_heap_committed_mb=_to_float(row.get("java_heap_committed_mb")),
                thread_committed_mb=_to_float(row.get("thread_committed_mb")),
                code_committed_mb=_to_float(row.get("code_committed_mb")),
                gc_committed_mb=_to_float(row.get("gc_committed_mb")),
                internal_committed_mb=_to_float(row.get("internal_committed_mb")),
                other_committed_mb=_to_float(row.get("other_committed_mb")),
            )
        )

    if not samples:
        raise ValueError(f"CSV has no parseable rows: {csv_path}")

    samples.sort(key=lambda sample: sample.timestamp)

    if skipped_rows:
        print(f"Skipped malformed rows: {skipped_rows}")

    return samples


def moving_average(values: Sequence[float], window: int) -> List[float]:
    if window <= 1:
        return list(values)

    out: List[float] = []
    running_sum = 0.0
    for i, value in enumerate(values):
        running_sum += value
        if i >= window:
            running_sum -= values[i - window]
        count = min(i + 1, window)
        out.append(running_sum / count)
    return out


def plot(samples: List[Sample], out: Path, title: str, smooth_window: int) -> None:
    x = [s.timestamp for s in samples]

    committed_values = [s.total_committed_mb for s in samples]
    non_nmt_values = [s.non_nmt_estimated_mb for s in samples]
    jni_likely_values = [s.jni_likely_estimated_mb for s in samples]
    rss_values = [s.rss_mb for s in samples]

    smooth_committed = moving_average(committed_values, smooth_window)
    smooth_non_nmt = moving_average(non_nmt_values, smooth_window)
    smooth_jni_likely = moving_average(jni_likely_values, smooth_window)
    smooth_rss = moving_average(rss_values, smooth_window)

    fig, (ax_total, ax_components) = plt.subplots(2, 1, figsize=(13, 8), sharex=True)

    if smooth_window > 1:
        ax_total.plot(x, committed_values, linewidth=1.0, alpha=0.3, label="NMT committed (raw)")
        ax_total.plot(x, non_nmt_values, linewidth=1.0, alpha=0.3, label="non-NMT estimated (raw)")
        ax_total.plot(x, jni_likely_values, linewidth=1.0, alpha=0.3, label="JNI-likely estimated (raw)")
        ax_total.plot(x, rss_values, linewidth=1.0, alpha=0.3, linestyle="--", label="RSS (raw)")

    suffix = f" (MA{smooth_window})" if smooth_window > 1 else ""
    ax_total.plot(x, smooth_committed, label=f"NMT committed{suffix}", linewidth=2)
    ax_total.plot(x, smooth_non_nmt, label=f"non-NMT estimated (rss - committed){suffix}", linewidth=2)
    ax_total.plot(x, smooth_jni_likely, label=f"JNI-likely estimated{suffix}", linewidth=2)
    ax_total.plot(x, smooth_rss, label=f"RSS{suffix}", linewidth=1.6, linestyle="--")
    ax_total.set_ylabel("MB")
    ax_total.grid(True, alpha=0.25)
    ax_total.legend(loc="upper left")
    ax_total.set_title(title)

    ax_components.plot(x, [s.java_heap_committed_mb for s in samples], label="Java Heap")
    ax_components.plot(x, [s.thread_committed_mb for s in samples], label="Thread")
    ax_components.plot(x, [s.code_committed_mb for s in samples], label="Code")
    ax_components.plot(x, [s.gc_committed_mb for s in samples], label="GC")
    ax_components.plot(x, [s.internal_committed_mb for s in samples], label="Internal")
    ax_components.plot(x, [s.other_committed_mb for s in samples], label="Other")
    ax_components.set_ylabel("MB")
    ax_components.set_xlabel("Time")
    ax_components.grid(True, alpha=0.25)
    ax_components.legend(loc="upper left", ncol=3)

    fig.autofmt_xdate()
    fig.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, dpi=160)


def main() -> int:
    args = parse_args()
    samples = load_samples(args.csv_path)

    if args.last > 0:
        samples = samples[-args.last :]

    if len(samples) < 2:
        raise ValueError("Need at least 2 samples to produce a meaningful chart")

    if args.smooth_window < 1:
        raise ValueError("--smooth-window must be >= 1")

    plot(samples, args.out, args.title, args.smooth_window)
    print(f"Wrote PNG: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

